// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pgstore

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Bid struct {
	ID        uuid.UUID          `json:"id"`
	ProductID uuid.UUID          `json:"product_id"`
	BidderID  uuid.UUID          `json:"bidder_id"`
	BidAmount float64            `json:"bid_amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID           uuid.UUID          `json:"id"`
	SellerID     uuid.UUID          `json:"seller_id"`
	ProductName  string             `json:"product_name"`
	Description  string             `json:"description"`
	BasePrice    float64            `json:"base_price"`
	AuctionStart pgtype.Timestamptz `json:"auction_start"`
	AuctionEnd   pgtype.Timestamptz `json:"auction_end"`
	IsSold       bool               `json:"is_sold"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	Token  string             `json:"token"`
	Data   []byte             `json:"data"`
	Expiry pgtype.Timestamptz `json:"expiry"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	UserName     string             `json:"user_name"`
	Email        string             `json:"email"`
	PasswordHash []byte             `json:"password_hash"`
	Bio          string             `json:"bio"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
